name: creaconsulta_03
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.8.1 <4.0.0' # Ajustado para tu versión de Dart

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  intl: ^0.19.0

  # Dependencias para la captura de pantalla y manejo de imágenes
  screenshot: ^3.0.0
  universal_html: ^2.2.0 # Necesario para guardar en web
  image: ^4.1.4
  permission_handler: ^11.0.1 # Para permisos en Android/iOS
  path_provider: ^2.1.1 # Para encontrar rutas de guardado en Android/iOS

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0 # Versión común de lints. Si hay algún problema, la podemos ajustar.

flutter:
  uses-material-design: true

  # Para la imagen de la bandera del Zulia
  assets:
    - assets/images/bandera_zulia.png # Asegúrate de que este sea el nombre y la ruta de tu imagen.
    # O si quieres incluir todas las imágenes de la carpeta:
    # - assets/images/