name: creaconsulta_03
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.8.1 <4.0.0' # AJUSTADO: Usa la versión de Dart 3.10.0 (estable con Flutter 3.22.x)

dependencies:
  flutter:
    sdk: flutter

  # Dependencias generales del proyecto (algunas de las 13 conflictivas originales)
  cupertino_icons: ^1.0.6 # Mantener la restricción de versión estándar
  intl: ^0.19.0 # Restablecida la restricción, si causa conflicto después, la ajustaremos

  # Dependencias para la captura de pantalla y manejo de imágenes
  screenshot: ^3.0.0 # Una versión común, si no la tienes, ajusta o déjala sin ^
  universal_html: ^2.2.0 # Versión común
  image: ^4.1.0 # Versión común
  permission_handler: ^12.0.0+1 # Versión recomendada por los logs anteriores
  path_provider: ^2.1.3 # Versión común

  # Dependencias que fueron problemáticas y posiblemente estaban ausentes o mal configuradas
  # Se añaden con la restricción de versión más abierta para que 'flutter pub get' las resuelva.
  # Estas son las que estaban en tu lista de 13 y no las vi en tu pubspec.yaml actual.
  flutter_lints: ^3.0.2 # Se asume una versión base, si da problemas, se puede relajar a solo `flutter_lints:`
  lints: ^3.0.0 # Se asume una versión base, si da problemas, se puede relajar a solo `lints:`
  leak_tracker: ^10.0.9
  leak_tracker_flutter_testing: ^3.0.9
  leak_tracker_testing: ^3.0.1
  material_color_utilities: ^0.11.1
  meta: ^1.16.0
  test_api: ^0.7.4
  vector_math: ^2.1.4
  vm_service: ^15.0.0
  # permission_handler_android: ^13.0.1 # Ya incluida en permission_handler, suele ser transitiva, pero la dejo si la tenías explícita.


dev_dependencies:
  flutter_test:
    sdk: flutter
  # Si tienes otras dev_dependencies, agrégalas aquí con sus versiones

flutter:
  uses-material-design: true

  assets:
    - assets/images/bandera_zulia.png
  # Si quieres incluir todas las imágenes de la carpeta, puedes usar:
  # - assets/images/