name: Deploy Flutter Web to GitHub Pages

on:
  push:
    branches:
      - main # ¡IMPORTANTE! Asegúrate de que esta es tu rama principal (main o master)

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: 'Get Flutter dependencies'
        run: flutter pub get

      - name: 'Build Flutter web'
        # Comando actualizado para asegurar la salida correcta
        run: |
          flutter build web --release --base-href /crealf/
          ls -la build/web/ # Añadimos este comando para depuración, veremos qué hay en la carpeta

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web
          # user_name: 'github-actions[bot]'
          # user_email: 'github-actions[bot]@users.noreply.github.com'
          cname: