name: Implementar Flutter web en Github Pages

on:
  push:
    branches:
      - main # Asegúrate de que esta es tu rama principal (main o master)

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Permiso para escribir en el repositorio (necesario para el artifact)
      pages: write    # Permiso necesario para desplegar en GitHub Pages
      id-token: write # Necesario para la autenticación en GitHub Pages

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }} # Asegura la autenticación al clonar el repositorio, crucial para permisos de escritura.

      - name: Configurar Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable' # O 'beta' si estás usando ese canal de Flutter

      - name: Obtener dependencias de Flutter
        run: |
          flutter clean
          flutter pub get

      - name: Construir aplicación Flutter web
        run: |
          flutter build web --release --base-href=/crealf/ # Asegúrate que '/crealf/' es el base-href correcto para tu sitio GitHub Pages

      - name: Cargar artefacto para despliegue en Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: './build/web' # Directorio de salida de la compilación web de Flutter

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build # Este trabajo depende del trabajo 'build'
    steps:
      - name: Desplegar en GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 # Acción para desplegar el artefacto a GitHub Pages