name: Deploy Flutter Web to GitHub Pages

on:
  push:
    branches:
      - main # ¡IMPORTANTE! Asegúrate de que esta es tu rama principal (main o master)

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: 'Flutter clean' # Añadido: Limpia el proyecto
        run: flutter clean

      - name: 'Enable Flutter web config' # Añadido: Asegura la configuración web
        run: flutter config --enable-web

      - name: 'Get Flutter dependencies'
        run: flutter pub get

      - name: 'Build Flutter web'
        run: |
          flutter build web --release --base-href /crealf/
          ls -la build/web/ # Este comando nos ayudará a verificar la salida

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web
          cname: