name: Deploy Flutter Web to GitHub Pages

on:
  push:
    branches:
      - main # Asegúrate de que esta es tu rama principal (main o master)

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }} 

      - name: Initial Environment & Directory Check
        run: |
          echo "--- Initial Environment Check ---"
          echo "Current working directory:"
          pwd # Muestra el directorio actual

          echo "Listing contents of the root directory (recursively):"
          ls -laR . # Lista todo el contenido del repositorio de forma recursiva.
          echo "Checking if 'web/index.html' exists at the root:"
          test -f web/index.html && echo "web/index.html FOUND" || echo "web/index.html NOT FOUND"
          echo "-----------------------------------"

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Flutter clean and Get dependencies
        run: |
          echo "--- Running Flutter clean ---"
          flutter clean
          echo "--- Getting Flutter dependencies ---"
          flutter pub get

      - name: 'Build Flutter web'
  run: |
    echo "--- Starting Flutter web build ---"
    # Intenta compilar la aplicación Flutter para la web con más verbosidad para depuración.
    # Especificamos el target explícitamente para asegurar que lib/main.dart sea encontrado.
    flutter build web --release --base-href /crealf/ --verbose --target=lib/main.dart > flutter_build_web_log.txt 2>&1
    BUILD_EXIT_CODE=$? # Captura el código de salida del comando flutter build

    echo "--- Flutter web build completed with exit code: $BUILD_EXIT_CODE ---"
    echo "Content of flutter_build_web_log.txt (verbose output):"
    cat flutter_build_web_log.txt # Muestra el log completo de la compilación
    echo "--------------------------------------------------------"

    # ... (el resto del script de verificación y copia contingente permanece igual) ...

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web
          cname: