name: Deploy Flutter Web to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: # A침adimos esto para darle permisos a la acci칩n
      contents: write # Permiso para escribir en el repositorio (para gh-pages)
      pages: write # Permiso para desplegar en GitHub Pages
      id-token: write # Necesario para la autenticaci칩n en p치ginas

    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: 'Flutter clean'
        run: flutter clean

      - name: 'Enable Flutter web config'
        run: flutter config --enable-web

      - name: 'Get Flutter dependencies'
        run: flutter pub get

      - name: 'Build Flutter web'
        run: |
          flutter build web --release --base-href /crealf/
          ls -la build/web/ # Dejamos esto para verificar la salida en los logs

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web
          # user_name: 'github-actions[bot]'
          # user_email: 'github-actions[bot]@users.noreply.github.com'
          cname: