name: Implementar Flutter web en Github Pages
on:
  push:
    branches:
      - main # Asegúrate de que esta sea tu rama principal

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 # Paso para clonar tu repositorio

      - name: Listar archivos del repositorio para depurar # <-- NUEVO: Paso para depuración
        run: |
          echo "Contenido del directorio raíz del repositorio:"
          ls -al
          echo ""
          echo "Contenido de .github/:"
          ls -al .github
          echo ""
          echo "Contenido de .github/workflows/:"
          ls -al .github/workflows

      - name: Configurar Flutter SDK # Se usará la versión 3.22.2
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.2' # Versión de Flutter que el runner tiene y tu proyecto ahora soporta

      - name: Obtener dependencias de Flutter
        run: flutter pub get

      - name: Construir aplicación Flutter web
        run: flutter build web --release

      - name: Desplegar en GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }} # Despliega solo si estás en la rama 'main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }} # Token de GitHub, ya configurado automáticamente
          publish_dir: ./build/web # Carpeta donde Flutter genera los archivos web