name: Deploy Flutter Web to GitHub Pages

on:
  push:
    branches:
      - main # Asegúrate de que esta es tu rama principal (main o master)

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }} 

      - name: Initial Environment & Directory Check
        run: |
          echo "--- Initial Environment Check ---"
          echo "Current working directory:"
          pwd # Muestra el directorio actual

          echo "Listing contents of the root directory (recursively):"
          ls -laR . # Lista todo el contenido del repositorio de forma recursiva.
          echo "Checking if 'web/index.html' exists at the root:"
          test -f web/index.html && echo "web/index.html FOUND" || echo "web/index.html NOT FOUND"
          echo "-----------------------------------"

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Flutter clean and Get dependencies
        run: |
          echo "--- Running Flutter clean ---"
          flutter clean
          echo "--- Getting Flutter dependencies ---"
          flutter pub get

      - name: Build Flutter web
  run: |
    echo "--- Starting Flutter web build ---"
    echo "Forzando limpieza agresiva de compilación web..."
    rm -rf build/web # Elimina la carpeta build/web por completo si existe.
    flutter clean --web # Limpia caché específica de web.

    echo "Iniciando 'flutter build web'..."
    flutter build web --release --base-href /crealf/

    echo "--- Checking build/web/ contents after Flutter build ---"
    # Muestra contenido del directorio esperado, ahora esperamos que exista después de la compilación
    ls -laR build/web/ && echo "build/web/ directory found and contents listed." || echo "build/web/ directory NOT FOUND or EMPTY after Flutter build."
    echo "--------------------------------------------------------"

    # Comprueba si index.html fue generado por flutter build.
    if [ ! -f build/web/index.html ]; then
      echo "********************************************************"
      echo "ADVERTENCIA: 'index.html' was NOT generated by 'flutter build web'."
      echo "Attempting to copy 'web/index.html' as a contingency."

      # Asegura que build/web directory exists before copying, critical if flutter build failed to create it.
      mkdir -p build/web

      echo "Verifying 'web/index.html' path before copy:"
      test -f web/index.html && echo "web/index.html FOUND before copy." || echo "web/index.html NOT FOUND before copy. THIS IS A CRITICAL PROBLEM!"

      # Perform the copy
      cp web/index.html build/web/index.html || echo "Error copying web/index.html to build/web/index.html. Check source path or permissions."

      echo "Checking build/web/ contents AGAIN after contingency copy:"
      ls -laR build/web/ || echo "build/web/ directory still not found or empty after copy."

      echo "********************************************************"

      # Final check after contingency copy. If still not found, it's a critical error.
      if [ ! -f build/web/index.html ]; then
        echo "ERROR: 'index.html' is still missing in 'build/web/' even after contingency copy."
        echo "Full 'build/' directory contents (diagnostic):"
        ls -laR build/ || true
        echo "Flutter Doctor (verbose):"
        flutter doctor -v
        echo "Searching for Flutter log files:"
        find . -name "flutter_*.log" || true
        exit 1 # Fail the step if index.html is truly missing.
      fi
    fi
    echo "index.html successfully ensured in 'build/web/'."
    ls -la build/web/ # Final confirmation of content

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web
          cname: