name: Deploy Flutter Web to GitHub Pages

on:
  push:
    branches:
      - main # Asegúrate de que esta es tu rama principal

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: 'Flutter clean'
        run: flutter clean

      - name: 'Enable Flutter web config'
        run: flutter config --enable-web

      - name: 'Get Flutter dependencies'
        run: flutter pub get

      - name: 'Build Flutter web'
        run: |
          mkdir -p build/web # Asegura que el directorio exista (aunque flutter build lo haría)
          flutter build web --release --base-href /crealf/
          # Verificar si index.html existe después de la compilación
          if [ ! -f build/web/index.html ]; then
            echo "Error: index.html not found in build/web/ after compilation."
            ls -R build/ # Lista todo el contenido del directorio build para depuración
            exit 1
          fi
          echo "index.html successfully generated."
          ls -la build/web/ # Confirma el contenido

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web
          cname: